/* Sometimes is usefull to pull the columns of tables concatend by ',' or another separator */

/* STRING_AGG is available only from SQL Server 2017 */

SELECT [TABLE_NAME], STRING_AGG(QUOTENAME([COLUMN_NAME]), ',') AS [COLUMNS]
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [TABLE_NAME] LIKE N'Pippo'
GROUP BY [TABLE_NAME]

/* Without using STRING_AGG */

SELECT DISTINCT C.[TABLE_NAME]
	, LEFT(A.[COLUMNS], LEN(A.[COLUMNS]) - 1) AS [COLUMNS]
FROM [INFORMATION_SCHEMA].[COLUMNS] C
CROSS APPLY
(
	SELECT QUOTENAME([COLUMN_NAME]) + N','
	FROM [INFORMATION_SCHEMA].[COLUMNS] B
	WHERE C.[TABLE_NAME] = B.[TABLE_NAME] 
	FOR XML PATH(N'')

) A ([COLUMNS])
WHERE C.[TABLE_NAME] LIKE N'Pippo'

